kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: golang:1.16
    commands:
      - go run . --source ./sample/original.json --destination ./sample/duplicate.sjon
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - coverage.txt
